"""Subclass of FramePrincipal, which is generated by wxFormBuilder."""

import wx
import guiperfumes
from ProjSisPerfumesFrameMarca import ProjSisPerfumesFrameMarca
from ProjSisPerfumesFramePerfumesGrid import ProjSisPerfumesFramePerfumesGrid

# Implementing FramePrincipal
class ProjSisPerfumesFramePrincipal( guiperfumes.FramePrincipal ):
	def __init__( self, parent ):
		guiperfumes.FramePrincipal.__init__( self, parent )
		self.frameMarca=None
		self.framePerfume=None

	# Handlers for FramePrincipal events.
	def fecharFramePrincipal( self, event ):
		self.Destroy()

	def abrirMarca( self, event ):
		if not self.frameMarca:
			self.frameMarca=ProjSisPerfumesFrameMarca(self)
		self.frameMarca.Show(True)

	def abrirFixacoes( self, event ):
		# TODO: Implement abrirFixacoes
		pass

	def abrirVolumes( self, event ):
		# TODO: Implement abrirVolumes
		pass

	def abrirPerfume( self, event ):
		if not self.framePerfume:
			self.framePerfume=ProjSisPerfumesFramePerfumesGrid(self)
		self.framePerfume.Show(True)

	def fecharApp( self, event ):
		# TODO: Implement fecharApp
		pass


